#!/bin/bash
useragent() {
useragentlist="'1' '2' '3' '4' '5' '6'"
IFS=$'\n'
useragent=('1' '2' '3' '4')
userandom=()
function checkArray
{
 for item in ${userandom[@]}
 do
 [[ "$item" == "$1" ]] && return 0
 done
 return 1
}
while [ "${#userandom[@]}" -ne "${#useragent[@]}" ]
do
 rand=$[ $RANDOM % ${#useragent[@]} ] 
 checkArray "${useragent[$rand]}" || userandom=(${userandom[@]} "${useragent[$rand]}")
done
}

webproxy() {
webproxylist="'1' '2' '3' '4' '5' '6'"
IFS=$'\n'
proxy=('1' '2' '3' '4')
proxyrandom=()
function checkArray
{
 for item in ${proxyrandom[@]}
 do
 [[ "$item" == "$1" ]] && return 0
 done
 return 1
}
while [ "${#proxyrandom[@]}" -ne "${#proxy[@]}" ]
do
 rand=$[ $RANDOM % ${#proxy[@]} ] 
 checkArray "${proxy[$rand]}" || proxyrandom=(${proxyrandom[@]} "${proxy[$rand]}")
done
}
